language: bash
services: docker

env:
  - VERSION=9.1
  - VERSION=9.2
  - VERSION=9.3
  - VERSION=9.4
  - VERSION=9.5
  - VERSION=9.6

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - image="alpine-postgres:$VERSION"

script:
  - docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=onjin/alpine-postgres
  - 

# vim:set et ts=2 sw=2:
